### ISSUE TITLE
Would this web-based Medusa POS work with Square's Terminal?

### ISSUE THREAD

**Issue by mrfzd** [pavlotsyhanok/medusa-pos-react#3]
Would this POS work with Square POS-based Terminal?
If not, how hard is it to integrate Square into this?
Could you please explain your approach to building and baking Stripe's POS Terminal?

Note: The Square's POS Terminal is based on webhooks and it triggers events to your webhooks endpoint, for example, if we want to trigger the Square's Terminal to respond to any web-based POS system including this one, we have to make an API call to our registered Square Terminal via Square's cloud-based infrastructure via their specified APIs!

However, I'm not sure if Stripe's is close or similar to Square's based on what I explained above!

I would appreciate any direction and help from you, I'm also happy to contribute to this project in case anyone else is looking to integrate Square's Terminal payment systems.

Many thanks

https://developer.squareup.com/docs/terminal-api/overview
https://squareup.com/gb/en/hardware/terminal

**Comment by pavlotsyhanok** [comment]
@mrfzd Thank you for your message.

The current version is intended to work with Stripe Terminal. However, support for Square is also planned. Inherently, they are not too different in implementation; the payment system node would be replaced with Square integration instead of Stripe. Square also has great support for cases like this.

Here is a brief representation of how it would look:

![image](https://github.com/pavlotsyhanok/medusa-pos-react/assets/130260096/7d82a6b1-f894-4745-9e46-2e8d5ed30bb8)

**Comment by mrfzd** [comment]
Thank you, Pavlo :)
